apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
        - name: heart-api
          image: heart-mlops-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
